version: '3.3'

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - ./src/.env
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      - web

  web:
    build: ./src
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./src/.env