version: '3.3'

services:
  web:
    build: ./core
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    env_file:
      - ./core/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./core/.env