version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_PASSWORD=12345
      - DJANGO_SUPERUSER_EMAIL=root@root.com
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
